version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 75
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 75
