# Generated by Django 3.0 on 2019-12-08 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_op', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/d09510be-27d8-4b12-8d99-b4d7f98d6e2e/'),
        ),
    ]
